name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.python_ver }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python_ver }}

    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt -t ./lib
        zip -r tmdb-flow-plugin.zip . -x '*.git*' -x '*.github*' -x '*.zip' -x '*.pyc' -x '__pycache__/*' -x '*.log' -x 'popular_movies_cache.json'

    - name: Publish
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: 'tmdb-flow-plugin.zip'
        tag_name: "v${{steps.version.outputs.prop}}"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 